# Site settings
email: justinalfonso29@hotmail.com
baseurl:
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jalfonze
description: Justin Alfonso, a graduate musician, chef by trade and a traveller at heart. Jalfonze is a philosphy I have created on my own experiences, a blog on my thoughts and travels. Come follow me on my journey so far.
url: "https://jalfonze.com"
twitter_username:
default_img: https://i.lensdump.com/i/O7eX5.jpg

# Profile settings
name: Justin Alfonso
profile_img: https://i.lensdump.com/i/dxD6m.jpg
profile: A dreamer born in Manila, Philippines but raised in Brighton, England. A graduate musician, chef by trade and a traveller at heart. Live the life you love and love the life you live.
social:
  instagram: https://www.instagram.com/jalfonze
  facebook: https://www.facebook.com/jalfonze
  youtube: https://www.youtube.com/user/SluggerBrighton
  pinterest: https://www.pinterest.com.au/jalfonze1/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Plugins
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
